# This workflow will build the Velocity jar with Gradle and create a new release with it.

name: Build Velocity JAR
on: [push]
permissions:
  actions: read
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: velocity-jar
          path: build/libs
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{github.run_number}}
          files: velocity-jar