# This workflow will build the Velocity jar with Gradle and create a new release with it.

name: Build Velocity JAR
on: [push]
permissions:
  actions: read
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{github.run_number}}
          files: proxy/build/libs/velocity-proxy-release-all.jar